Controllers/AppController.cs
using MastersOfCinema.Data;
using MastersOfCinema.Data.Entities;
using MastersOfCinema.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace MastersOfCinema.Controllers
{
    public class AppController : Controller
    {
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly Context context;
        private readonly ICinemaRepository repo;

        public AppController(IHttpContextAccessor httpContextAccessor, Context context,
            ICinemaRepository repo)
        {
            this.httpContextAccessor = httpContextAccessor;
            this.context = context;
            this.repo = repo;
        }
        public IActionResult Index()
        {
            

            /*Start popular Review section*/
            //Get the id of the most liked reviews
            var reviews = context.LikeReview
                                    .GroupBy(q => q.ReviewId)
                                    .OrderByDescending(gp => gp.Count())
                                    .Take(6)
                                    .Select(g => g.Key).ToList();


            //Convert the selected reviews into ReviewViewModel
            List<ReviewViewModel> PopularReviews = new List<ReviewViewModel>();
            foreach (var item in reviews)
            {
                PopularReviews.Add(repo.GetReviewLikeStatsById(item));
                //item.User = item.User;
            }
            //add movies info to each review
            foreach(var item2 in PopularReviews)
            {
                item2.ReviewdMovie = context.Movies
                    .Where(m => m.Id == item2.MovieId).FirstOrDefault();
            }
            /*End popular Review section*/

            /*Select 3 lists manually*/
            List<CList> selectedLists = new List<CList>();
            selectedLists.Add(repo.GetListsList().Where(i => i.Id == 34).FirstOrDefault());
            selectedLists.Add(repo.GetListsList().Where(i => i.Id == 12).FirstOrDefault());
            selectedLists.Add(repo.GetListsList().Where(i => i.Id == 24).FirstOrDefault());


            HomePageViewModel homePageViewModel;
            if (User.Identity.IsAuthenticated)
            {
                //Id of the current user
                var id = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                //Current user
                User user = context.Users.Where(i => i.Id == id).FirstOrDefault();
                homePageViewModel = new HomePageViewModel()
                {
                    ///
                    PopularLists = new CListsViewModel() { Lists = selectedLists },
                    User = user,
                    PopularReviews = PopularReviews,
                };
            } else
            {
                homePageViewModel = new HomePageViewModel()
                {
                    ///
                    PopularLists = new CListsViewModel() { Lists = selectedLists },
                    //User = user,
                    PopularReviews = PopularReviews,
                };
            }


            /*Start highest rated movies section*/
            //Later create a list and manually choose highest rated movies
            var highRatedMovies =  new List<Movie>();
            highRatedMovies = repo.GetCustomList(20).Take(6).ToList();

            homePageViewModel.HighestRatedMovies = highRatedMovies;

            //List<MovieRating> high = new List<MovieRating>();
            /*foreach (var movie in context.MovieRatings)
            {
                if(repo.GetAverageRating(movie.Id) > 3.5)
                {
                    homePageViewModel.HighestRatedMovies.Add(context.Movies.Where(x => x.Id == movie.Id).FirstOrDefault());
                }
            }*/

            //homePageViewModel.HighestRatedMovies = homePageViewModel.HighestRatedMovies.Take(16).ToList();

            /*End highest rated movies section*/

            homePageViewModel.UserWatchlist = repo.GetWatchlist().Take(6).ToList();

            return View(homePageViewModel);
        }
    }
}

Views/Shared/_AjaxLoadAnimationPartial.cshtml
<div id="" class="text-center mt-2">
    <button id="load-more-movies-button" class="load-more-movies-button" type="button" name="name" value="Load more">
        <i class="fas fa-arrow-down loading-icon"></i>
        <div class="ld ld-pie ld-spin-fast"></div>
    </button>
</div>



@*Loading animation*@
<div id="loading-animation">
    <div class="loader-ellips">
        <span class="loader-ellips__dot"></span>
        <span class="loader-ellips__dot"></span>
        <span class="loader-ellips__dot"></span>
        <span class="loader-ellips__dot"></span>
    </div>
</div>

@*Message when reaching end*@
<div id="reached-end" class="mt-5 mb-2 text-center text-white fs-3">
    You reached the end!
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html  dir="ltr">
<head>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Masters of Cinema</title>
    @*<link rel="icon" type="image/x-icon" href="favicon.ico">*@
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body class="body">
    @*Navbar Start*@
    <div class="main-navigation-bg main-navigation-wrapper">
        <header class="container-xxl row mx-auto">
            <nav class="navbar navbar-expand-md navbar-dark">
                <a class="navbar-brand" asp-controller="App" asp-action="Index">
                    <img src="~/image/General/logo.svg" />
                </a>
                <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div id="navbarSupportedContent" class="collapse navbar-collapse">
                    <ul class="navbar-nav w-100">
                        <li class="nav-item"><a class="nav-link @Html.ActiveClass("App", "Index")" asp-controller="App" asp-action="Index">Home</a></li>
                        <li class="nav-item"><a class="nav-link @Html.ActiveClass("Director", "Index")" asp-controller="Director" asp-action="Index">Directors</a></li>
                        <li class="nav-item"><a class="nav-link @Html.ActiveClass("Movie", "Index")" asp-controller="Movie" asp-action="Index">Movies</a></li>
                        <li class="nav-item"><a class="nav-link @Html.ActiveClass("List", "Index")" asp-controller="List" asp-action="Index">Lists</a></li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item ms-md-auto nav-profile-picture-wrapper">
                                <a class="nav-link @Html.ActiveClass("Account", "Profile") @Html.ActiveClass("Account", "Films") @Html.ActiveClass("Account", "Watchlist") @Html.ActiveClass("Settings", "Index")
                                @Html.ActiveClass("Settings", "Email") @Html.ActiveClass("Settings", "ChangePassword") @Html.ActiveClass("Settings", "PersonalData")
                                @Html.ActiveClass("Account", "Ratings")"
                                   asp-controller="Settings" asp-action="Index">
                                    <vc:welcome-message></vc:welcome-message>
                                </a>
                            </li>
                            <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a></li>
                        }
                        else
                        {
                            <li class="nav-item ms-md-auto"><a class="nav-link me-auto" asp-area="Identity" asp-page="/Account/Register">Register</a></li>
                            <li class="nav-item"><a class="nav-link me-auto @Html.ActiveClass("Account", "Login")" asp-controller="Account" asp-action="Login">Login</a></li>
                        }
                    </ul>
                </div>
            </nav>
        </header>
    </div>
    @*Navbar End*@

    <section class="main-content pt-4">
        @RenderBody()
    </section>


    <footer id="footer" class="site-footer pb-3 pt-3">
        <div class="container-xl text-center text-sm-start">
            Copyright 2022 Masters of Cinema LLC
        </div>
    </footer>

    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_MovieListPartial.cshtml
@*Currently unused - replcaed by the ajax version*@

@model MovieListViewModel

<div class="director-info-page mt-2">
    @*The movies list section*@
    <div class="director-movies-container container">
        <div class="row px-1">
            @foreach (var item in Model.Movies)
            {
                <div class="director-list-item mt-3 mb-2 mt-lg-4 mb-lg-3 col-4 col-md-3 col-lg-2 px-0 px-lg-1">
                    <div class="mx-auto">
                        @*Movie poster and its tooltip (title (year)) *@
                        <div class="movie-poster-wrapper mx-auto">
                            <span class="movie-tooltip">@Html.DisplayFor(modelItem => item.Title) (@Html.DisplayFor(modelItem => item.Year))</span>
                            <a asp-controller="Movie" asp-action="Details" asp-route-id="@item.Id">
                                <img src="@("~/image/"+item.ImageName)" class="movie-poster" asp-append-version="true" />
                            </a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Views/Shared/_ProfileLayout.cshtml
@{
    Layout = "_Layout";
}

@*Navbar Start*@
<div class="container main-navigation-bg">
    <header class="container-xxl profile-navigation-container row mx-auto">
        <nav class="navbar navbar-expand navbar-dark">

            <div id="navbarSupportedContent" class="collapse navbar-collapse">
                <ul class="navbar-nav w-100 d-inline-block text-center">
                    <li class="nav-item d-inline-block"><a class="nav-link @Html.ActiveClass("Settings", "Index") @Html.ActiveClass("Settings", "Email") @Html.ActiveClass("Settings", "ChangePassword") @Html.ActiveClass("Settings", "PersonalData")" asp-controller="Settings" asp-action="Index">Settings</a></li>

                    <li class="nav-item d-inline-block"><a class="nav-link @Html.ActiveClass("Account", "Films")" asp-controller="Account" asp-action="Films">Films</a></li>
                    <li class="nav-item d-inline-block"><a class="nav-link @Html.ActiveClass("Account", "Watchlist")" asp-controller="Account" asp-action="Watchlist">Watchlist</a></li>
                    <li class="nav-item d-inline-block"><a class="nav-link @Html.ActiveClass("Account", "Ratings")" asp-controller="Account" asp-action="Ratings">Ratings</a></li>
                    <li class="nav-item d-inline-block"><a class="nav-link @Html.ActiveClass("Account", "UserLists")" asp-controller="Account" asp-action="UserLists">My Lists</a></li>
                </ul>
            </div>
        </nav>
    </header>
</div>
@*Navbar End*@

@*Render the main view*@
@RenderBody()


@section Scripts {
    <partial name="_ValidationScriptsPartial" />

}

Views/Shared/_ProfileSettingsLayout.cshtml
@{
    Layout = "_ProfileLayout";
}

<div class="container mt-2">
    <h2 class="text-center text-md-start">Manage your account</h2>
    <h4 class="text-center text-md-start">Change your account settings</h4>
    <hr />
    <div class="row">
        <div class="col-md-3 mb-3 text-center text-md-start">
            <partial name="_ManageNav" />
            <hr />
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>