ViewModels/ReviewViewModel.cs
using MastersOfCinema.Data.Entities;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace MastersOfCinema.ViewModels
{
    public class ReviewViewModel
    {
        [Key]
        public int Id { get; set; }
        public User User { get; set; }
        public int MovieId { get; set; }
        public string ReviewText { get; set; }
        public int LikeCount { get; set; }
        public bool IsLiked { get; set; }
        public int? ReviewerRate { get; set; }
        public List<LikeReview> Likers { get; set; }
        //For homepage only - to display the movie poster
        public Movie ReviewdMovie { get; set; }
    }
}

//Each review in a page is displayed by this
//including like count and also determining if this review is liked by the user or not

Controllers/ReviewController.cs
using MastersOfCinema.Data;
using MastersOfCinema.Data.Entities;
using MastersOfCinema.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MastersOfCinema.Controllers
{
    public class ReviewController: Controller
    {
        private readonly Context context;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly ICinemaRepository repository;
        private readonly UserManager<User> userManager;

        public ReviewController(Context context,
            IWebHostEnvironment webHostEnvironment,
            ICinemaRepository repository,
            UserManager<User> userManager)
        {
            this.context = context;
            this.webHostEnvironment = webHostEnvironment;
            this.repository = repository;
            this.userManager = userManager;
        }
        [HttpGet]
        public async Task<IActionResult> PopularReview()
        {
            //List<ReviewViewModel> popularRevs = new List<ReviewViewModel>();

            /*Start popular Review section*/
            //Get the id of the most liked reviews
            var reviews = context.LikeReview
                                    .GroupBy(q => q.ReviewId)
                                    .OrderByDescending(gp => gp.Count())
                                    .Take(12)
                                    .Select(g => g.Key).ToList();


            //Convert the selected reviews into ReviewViewModel
            List<ReviewViewModel> PopularReviews = new List<ReviewViewModel>();
            foreach (var item in reviews)
            {
                PopularReviews.Add(repository.GetReviewLikeStatsById(item));
                //item.User = item.User;
            }
            //add movies info to each review
            foreach (var item2 in PopularReviews)
            {
                item2.ReviewdMovie = context.Movies
                    .Where(m => m.Id == item2.MovieId).FirstOrDefault();
            }
            /*End popular Review section*/

            return View(PopularReviews);
        }


        //Post review - save it to database - display it
        [HttpPost]
        public async Task<IActionResult> Review(MovieRateDirector movieRateDirector)
        {
            //Only need to get movieId and the review text from view
            //Need to set a movieId and User to the new record

            //Start saving the review
            //create a new review object for saving into database
            Review newReview = new Review()
            {
                //add review text
                ReviewText = movieRateDirector.UserReview.ReviewText

            };
            //add movie Id
            var movieId = movieRateDirector.UserReview.MovieId;
            newReview.MovieId = movieId;

            //add user (reviewer)
            var UserName = HttpContext.User.Identity.Name;
            newReview.User = context.Users.FirstOrDefault(u => u.UserName == UserName);

            newReview.Id = 0;

            if (ModelState.IsValid)
            {
                //Save (Create or update) rating in DB
                context.Update(newReview);
                await context.SaveChangesAsync();
            }
            //End saving the review

            //create a new model for sending the new review to the view
            MovieRateDirector movieRateDirector2 = new MovieRateDirector();

            //add like count and isLiked to the new review
            //(probably would be better to add them manually: likeCount = 0, isLiked = false)
            movieRateDirector2.UserReview = repository.GetReviewsLikeStats(newReview);

            //Display the new review
            return PartialView("Review/_AjaxReview", movieRateDirector2);
            //End create and send model
        }

        //Like / Unlike a review
        [HttpPost]
        public async Task<IActionResult> LikeReview(int ReviewId)
        {
            //If user not logged in, they can't like review
            if (User.Identity.IsAuthenticated == false)
            {
                return BadRequest("You should login first");
            }

            //Only need to get Review Id from view
            //Need to set a Review Id and User to the new record
            LikeReview like = new LikeReview();
            var reviewId = ReviewId;
            //Check to see if this review had been liked by this user before
            var UserName = HttpContext.User.Identity.Name;

            like.User = context.Users.FirstOrDefault(u => u.UserName == UserName);

            //If true it had been liked by this user before (meaning user wants to unlike it now)
            bool wasLiked = context.LikeReview.Where(u => u.User.UserName == UserName).Any(m => m.ReviewId == ReviewId);

            //If wasLiked != true, it's a like request, else it's an unlike request
            if (!wasLiked)
            {
                //Create record
                like.Id = 0;
                like.ReviewId = ReviewId;
                if (ModelState.IsValid)
                {
                    //Save (Create) like in DB
                    context.Update(like);
                    await context.SaveChangesAsync();
                }
            }
            else //it's a delete (unlike) request
            {
                //Delete like
                var logItem = context.LikeReview.Where(u => u.User.UserName == UserName)
                .FirstOrDefault(m => m.ReviewId == ReviewId);
                context.LikeReview.Remove(logItem);
                await context.SaveChangesAsync();

            }
            return Ok("Form Data received!");
        }


        //Edit a review
        [HttpPost]
        public async Task<IActionResult> BeginEditReview(string reviewId)
        {
            //create a new model for sending the new review to the view
            //MovieRateDirector movieRateDirector = new MovieRateDirector();
            int id = Int32.Parse(reviewId);
            var existingUserReview = repository.GetReviewLikeStatsById(id);

            //create a function to get it by id directly

            //add like count and isLiked to the new review
            //(probably would be better to add them manually: likeCount = 0, isLiked = false)
            /*movieRateDirector.UserReview = repository.GetMovieReviews(1).FirstOrDefault();

            return PartialView("Review/_EditReviewPartial", movieRateDirector);*/

            MovieRateDirector movieRateDirector2 = new MovieRateDirector();

            Review review = context.Review.FirstOrDefault();
            //add like count and isLiked to the new review
            //(probably would be better to add them manually: likeCount = 0, isLiked = false)
            movieRateDirector2.UserReview = existingUserReview;

            //Display the new review
            return PartialView("Review/_EditReview", movieRateDirector2);
        }

        //Update a review
        [HttpPost]
        public async Task<IActionResult> UpdateReview(MovieRateDirector newTextId)
        {
            var review = await context.Review.Include(x => x.User).FirstOrDefaultAsync(m => m.Id == newTextId.UserReview.Id);
            var newText = newTextId.UserReview.ReviewText;

            //if (ModelState.IsValid)
            //{
            //the new text has to be different and also has to not be empty
            if (review.ReviewText != newText && newTextId.UserReview.ReviewText != "")
            {
                //If image not uploaded, assign the default photo
                review.ReviewText = newText;
            }

            var local = context.Set<Review>()
            .Local
            .FirstOrDefault(entry => entry.Id.Equals(review.Id));
            // check if local is not null 
            if (local != null)
            {
                // detach
                context.Entry(local).State = EntityState.Detached;
            }

            context.Update(review);
            await context.SaveChangesAsync();

            //create a new model for sending the new review to the view

            //add like count and isLiked to the new review
            //(probably would be better to add them manually: likeCount = 0, isLiked = false)
            newTextId.UserReview = repository.GetReviewLikeStatsById(review.Id);

            //}
            return PartialView("Review/_AjaxReview", newTextId);
        }


        [HttpPost]
        public async Task<IActionResult> CancelReview(MovieRateDirector newTextId)
        {
            var review = await context.Review.Include(x => x.User).FirstOrDefaultAsync(m => m.Id == newTextId.UserReview.Id);

            //add like count and isLiked to the new review
            //(probably would be better to add them manually: likeCount = 0, isLiked = false)
            newTextId.UserReview = repository.GetReviewLikeStatsById(review.Id);

            //}
            return PartialView("Review/_AjaxReview", newTextId);
        }


        //Delete a review
        [HttpPost]
        public async Task<IActionResult> DeleteReview(MovieRateDirector movieIdReviewId)
        {
            //int id = Int32.Parse(reviewId);
            //Define a methid for get review by id
            var reviewId = movieIdReviewId.UserReview.Id;
            var review = await context.Review.Include(x => x.User).FirstOrDefaultAsync(m => m.Id == reviewId);

            //delete the likes of the review too
            IEnumerable<LikeReview> reviewLikes = context.LikeReview.Where(x => x.ReviewId == review.Id).ToList();
            foreach (var item in reviewLikes)
            {
                context.LikeReview.Remove(item);
            }

            //delete the the review itself
            context.Review.Remove(review);

Views/ViewComponents/UserAvatarViewComponent.cs
using MastersOfCinema.Data;
using MastersOfCinema.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace MastersOfCinema.Views.ViewComponents
{
    public class UserAvatarViewComponent
        : ViewComponent
    {
        private readonly ICinemaRepository _repository;
        private readonly Context _context;
        private readonly string _userId;

        public UserAvatarViewComponent(ICinemaRepository repository, /*IHttpContextAccessor httpContextAccessor,*/
            Context context)
        {
            _repository = repository;
            _context = context;
            //_userId = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
        }

        public IViewComponentResult Invoke(string userId)
        {
            //FIX LATER - IF LOGGED IN >> THE USER SHOULD BE DISTINGUISHEd
            //(EX. for displaying his review on top, or for editing)


            //User user = _context.Users.Where(i => i.Id == _userId).FirstOrDefault();
            //Fix later - shouldn't be executed if db is not seeded
            //if (_context.Users.Any(x => x.Id == user.Id))
            //{
            //var Username = user.FirstName ?? user.UserName;
            User user = _context.Users.Where(x => x.Id == userId).FirstOrDefault();
            //user.ProfilePicture = Convert.ToBase64String(UserManager.GetUserAsync(User).Result.ProfilePicture);
                return View("Default", user);
            //}
            //Fix later - shouldn't be executed if no user is logged in
            //return View("Default");
        }
    }
}

Views/Shared/Review/_AjaxReview.cshtml
@model MovieRateDirector
@*Only for logged in users!*@
@*This partial view is for displaying the user review on the top of reviews*@
@*Will be rendered: when user opens the movie details view (if he has a reiew of that movie),
    when user just posts a review, and when user clicks save after editing his review*@

<div class="col-12 border-bottom-0 user-review" id="user-review-wrapper">

    @*Reviewer's avatar is displayed on the left side of each review*@
    @if (Model.UserReview.User.ProfilePicture != null)
    {
        <div class="profile-picture-medium-wrapper">
            <div class="profile-picture-medium">
                <img class="nav-profile-picture" src="data:image/*;base64,@(Convert.ToBase64String(Model.UserReview.User.ProfilePicture))">
            </div>
        </div>
    }
    else
    {
        <div class="profile-picture-medium-wrapper">
            <div class="profile-picture-medium">
                <i class="fas fa-user-circle me-0 nav-default-profile-picture fs-2"></i>
            </div>
        </div>
    }
    @*END Reviewer's avatar*@

    @*Start Review's right side*@
    <div class="d-inline-block review-main-col">
        @*Start Review's header*@
        <div class="review-head-wrapper">
            <div class="review-head">
                <div class="review-head-text">
                    Review by
                    <span class="review-name me-2">
                        @Model.UserReview.User.FirstName
                    </span>
                    @if (@Model.UserReview.ReviewerRate != null)
                    {
                        <div class="reviewer-rate-wrapper d-inline-block">

                            @Model.UserReview.ReviewerRate
                            @for (var i = 0; i < Model.UserReview.ReviewerRate; i++)
                            {
                                <span class="starGlowReview" id=""></span>

                            }
                        </div>
                    }
                </div>
            </div>
        </div>

        @*Start review text*@
        <div class="review-text-wrapper">
            <div class="review-text">
                <div class="read-more-object-text" style="white-space: pre-line;" id="user-existing-review">@Model.UserReview.ReviewText</div>
            </div>
        </div>
        @*End review text*@

        @*Start like section*@
    <div class="review-like-wrapper style-head" id="user-existing-review-stats">
        @*When clicking on this, review will be liked or unliked*@
        <span class="review-like-button" id="review-like-button">
            <input type="hidden" value="@Model.UserReview.Id" class="form-control input-small user-existing-review-id" id="review-id" />
            @if (Model.UserReview.IsLiked)
            {
                <span class="review-icon-liked" id="like-icon"></span>
                <span class="review-liked-text" id="like-caption">Liked</span>
            }
            else
            {
                <span class="review-icon-like" id="like-icon"></span>
                <span class="review-like-text" id="like-caption">Like Review</span>
            }
        </span>
        @*End When clicking on this, review will be liked or unliked*@

        <partial name="~/Views/Shared/Review/_LikersUserReview.cshtml" model="Model.UserReview" />
    </div>
        @*End like section*@
        @*Edit ... button*@
        <div class="edit-review-textarea-wrapper" id="edit-review-container">

        </div>
        <div class="review-edit-buttons">
            <input type="button" value="Edit" class="review-save-button" id="edit-review" />
            <input type="button" value="Delete" class="review-delete-button" id="delete-edit-review" />
            <input type="button" value="Cancel" style="display: none;" class="review-cancel-button" id="cancel-edit-review" />
        </div>

    </div>
    @*END Review's right side*@

</div>

Views/Shared/Review/_EditReview.cshtml
@model MovieRateDirector
@*Only for logged in users!*@
@*Display user's review on the top of reviews*@
@*when it's just posted and later when page loads by the user*@

@*This information will be sent to the controller to update the review*@


<form id="editForm" enctype="multipart/form-data" class="my-2">
    <input asp-for="@Model.UserReview.Id" type="hidden" value="@Model.UserReview.Id" class="form-control input-small" id="" />
    <div class="review-input-wrapper" id="review-edit">
        <textarea asp-for="@Model.UserReview.ReviewText" style="height: 180px;" type="" value="" placeholder="Add a review..." class="review-input" id="review-text-edit"></textarea>
    </div>
</form>

Views/Shared/Review/_EmptyReview.cshtml
@model MovieRateDirector

@*Used to render empty text area -- when user has just deleted his existing review*@


<form id="submitForm" enctype="multipart/form-data" class="my-2">
    <input asp-for="@Model.UserReview.MovieId" type="hidden" value="@Model.Movie.Id" class="form-control input-small" id="" />
    <div class="review-input-wrapper">
        <textarea asp-for="@Model.UserReview.ReviewText" type="" value="" placeholder="Add a review..." class="review-input" id="review-text"></textarea>
    </div>
    <div class="review-edit-buttons">
        <input type="button" value="Review" class="review-save-button" id="submit-review" />

    </div>

</form>

Views/Shared/Review/_LikersReview.cshtml
@model ReviewViewModel
@*
    Is created to make the parent view (_Review.cshtml, etx) cleaner
    When rendering the likers of each review, this partial view is being called
*@

@*below each review, there is a section like: x peopla liked this review*@
@if (Model.LikeCount > 0)
{
    <span class="likers-head-wrapper" id="likers-head-wrapper">

        @if(Model.LikeCount == 1 && Model.IsLiked)
        {
        @*The only one who like this review is this user*@
        @*We need to hide the element when user unlikes the review*@
        <span class="review-like-stats" id="like-count" style="display: inline-block;">
            @Model.LikeCount
        </span>
        <span id="review-stats"> people liked this review</span>
        }
        else
        {
        @*Other users liked this review*@
        @*No need to hide/show for this element*@
        <span class="review-like-stats" id="like-count" style="display: inline-block;">
            @Model.LikeCount
        </span>
        <span id="review-stats"> people liked this review</span>
        }
        <i style='font-size:20px' class='fas likers-arrow'>&#xf107;</i>
    </span>
}
else
{
<span class="likers-head-wrapper" id="likers-head-wrapper" style="display: none;">
    @*No one liked this review*@
    @*We need to show the element when user likes the review*@
    <span class="review-like-stats" id="like-count" style="display: inline-block;">
        @Model.LikeCount
    </span>
    <span id="review-stats">
        people liked this review
    </span>
    <i style='font-size:20px' class='fas likers-arrow'>&#xf107;</i>
</span>

}

@*End: x peopla liked this review*@


@*The actual list of likers of a review*@
@{
    var likes = Model.Likers.ToList().Take(5);
    var extraLikers = Model.LikeCount - 5;
}
<div class="likers-wrapper" @if (Model.IsLiked) { <text> id="review-isliked-true" </text> }>
    (Liked by: @foreach (var item in Model.Likers.ToList().Take(5))
    {
        <span>
            @item.User.FirstName@if (item.Equals(likes.FirstOrDefault()) && Model.IsLiked)
            {<text> (you)</text>}@if (!item.Equals(likes.LastOrDefault()))
            {<text>, </text>}

        </span>


    }@if(Model.LikeCount > 5)
    {<text> and @extraLikers more.</text>})
</div>
@*End The actual list of likers of a review*@

Views/Shared/Review/_LikersUserReview.cshtml
@model ReviewViewModel
@*
    Is created to make the parent view (_AjaxReview.cshtml, etx) cleaner
    When rendering the likers of the user review, this partial view is being called
    Is being called only when user is logged in and has a review of this movie!
*@

@*below the user review, there is a section like: x peopla liked this review*@

@if (Model.LikeCount > 0)
{
<span class="likers-head-wrapper" id="likers-head-wrapper">
    @if (Model.LikeCount == 1 && Model.IsLiked)
    {
        @*The only one who like user review is himsel!*@
        @*We need to hide the element when user unlikes the review*@
        <span class="review-like-stats" id="like-count" style="display: inline-block;">
            @Model.LikeCount
        </span>
        <span id="review-stats"> people liked this review</span>
    }
    else
    {
        @*Other users liked this review*@
        @*No need to hide/show for this element*@
        <span class="review-like-stats" id="like-count" style="display: inline-block;">
            @Model.LikeCount
        </span>
        <span id="review-stats"> people liked this review</span>
    }
    <i style='font-size:20px' class='fas likers-arrow'>&#xf107;</i>
</span>
}
else
{
<span class="likers-head-wrapper" id="likers-head-wrapper" style="display: none;">
    @*No one liked the user review*@
    @*We need to show the element when user likes the review*@
    <span class="review-like-stats" id="like-count" style="display: inline-block;">
        @Model.LikeCount
    </span>
    <span id="review-stats"> people liked this review</span>
    <i style='font-size:20px' class='fas likers-arrow'>&#xf107;</i>
</span>
}


        @*End: x peopla liked this review*@


        @*The actual list of likers of the user review*@
        @{
            var likes = Model.Likers.ToList();
        }

        <div class="likers-wrapper " @if (Model.IsLiked) { <text> id="review-isliked-true" </text> }>
            (Liked by: @foreach (var item in Model.Likers)
            {
                <span>
                    @item.User.FirstName@if (item.Equals(likes.FirstOrDefault()) && Model.IsLiked)
                    {<text> (you)</text>}@if (!item.Equals(likes.LastOrDefault()))
                    {<text>, </text>}
                </span>
            })
        </div>

        @*End The actual list of likers of the user review*@

Views/Shared/Review/_Review.cshtml
@model MovieRateDirector
@*Display all existing reviews when page loads - when user IS logged in*@

@foreach (var item in Model.Review)
{
    <div class="col-12 a-review">

        @*Reviewer's avatar is displayed on the left side of each review*@
        @if (item.User.ProfilePicture != null)
        {
            <div class="profile-picture-medium-wrapper">
                <div class="profile-picture-medium">
                    <img class="nav-profile-picture" src="data:image/*;base64,@(Convert.ToBase64String(item.User.ProfilePicture))">
                </div>
            </div>
        }
        else
        {
            <div class="profile-picture-medium-wrapper">
                <div class="profile-picture-medium">
                    <i class="fas fa-user-circle me-0 nav-default-profile-picture fs-2"></i>
                </div>
            </div>
        }
        @*END Reviewer's avatar*@

        @*Start Review's right side*@
        <div class="d-inline-block review-main-col">
            @*Start Review's header*@
            <div class="review-head-wrapper">
                <div class="review-head">
                    <div class="review-head-text">
                        Review by
                        <span class="review-name me-2">
                            @item.User.FirstName
                        </span>
                        @if (@item.ReviewerRate != null)
                        {
                            <div class="reviewer-rate-wrapper d-inline-block">

                                @item.ReviewerRate
                                @for (var i = 0; i < item.ReviewerRate; i++)
                                {
                                    <span class="starGlowReview" id=""></span>

                                }
                            </div>
                        }


                    </div>
                </div>
            </div>

            @*Start review text*@
            <div class="review-text-wrapper">
                <div class="review-text">
                    <div class="read-more-object-text" style="white-space: pre-line;">@item.ReviewText</div>
                </div>
            </div>
            @*End review text*@

            @*Start like section*@
        <div class="review-like-wrapper style-head" style="overflow: hidden;">
            @*When clicking on this, review will be liked or unliked*@
            <span class="review-like-button" id="review-like-button">
                <input type="hidden" value="@item.Id" class="form-control input-small" id="review-id" />
                @if (item.IsLiked)
                {
                    <span class="review-icon-liked" id="like-icon"></span>
                    <span class="review-liked-text" id="like-caption">Liked</span>
                }
                else
                {
                    <span class="review-icon-like" id="like-icon"></span>
                    <span class="review-like-text" id="like-caption">Like Review</span>
                }
            </span>
            @*End When clicking on this, review will be liked or unliked*@

            @*Start Review like stats*@
            <partial name="~/Views/Shared/Review/_LikersReview.cshtml" model="item" />
            @*await Html.PartialAsync("~/Views/Shared/Review/_ReviewLikers.cshtml", item)*@
            @*End Review stats*@

        </div>
            @*End like section*@
        </div>
        @*END Review's right side*@

    </div>
}



<script>
    
</script>

Views/Shared/Review/_ReviewMain.cshtml
@model MovieRateDirector
    @*Start Review section - when user is logged in*@
    <section class="container mb-5 mt-3 px-sm-2 ps-md-3 ps-lg-4 ps-xl-2">

        <div class="row">

            @*reviews wrapper*@
            <div class="col-12 py-3 review-section-wrapper">
                <h2 class="review-section-heading" id="user-review-section">
                    Your review
                </h2>


                @if (Model.UserReview != null)
                {
                    <div class="review-ajax-container">
                        <div class="review-body" id="post-review" style="">
                            <partial name="~/Views/Shared/Review/_AjaxReview.cshtml" />
                        </div>
                    </div>
                }

                @if (Model.UserReview == null)
                {
                    <div class="review-ajax-container 50">
                        <div class="review-body" id="post-review" style="display: none;">

                        </div>
                    </div>
                    <partial name="~/Views/Shared/Review/_EmptyReview.cshtml" />
                }

                @if (Model.Review.Count() > 0)
                {
                    <h2 class="review-section-heading">
                        <span>Reviews of </span><strong style="color: white;">@Model.Movie.Title</strong>
                    </h2>

                    <div class="review-ajax-container">
                        <div class="review-body">
                            <partial name="~/Views/Shared/Review/_Review.cshtml" />
                            @*@await Component.InvokeAsync("UserAvatar", new { userId = @item.User.Id })*@
                        </div>
                    </div>
                }
                else
                {
                    <h2 class="review-section-heading text-center" id="no-review-yet">
                        No reviews yet!
                    </h2>
                }
            </div>
        </div>
    </section>
    @*End Review section*@

<script src="~/lib/jquery/jquery.confirm.js"></script>
    <script src="~/js/review.js"></script>

Views/Shared/Review/_ReviewMainLimited.cshtml
@model MovieRateDirector
@*Start Review section - when user is not logged in*@
<section class="container mb-5 mt-3 px-sm-2 ps-md-3 ps-lg-4 ps-xl-2">

    <div class="row">
        @*reviews wrapper*@
        <div class="col-12 py-3 review-section-wrapper">


            @if (Model.Review.Count() > 0)
            {
            <h2 class="review-section-heading">
                <span>Reviews of </span><strong style="color: white;">@Model.Movie.Title</strong>
            </h2>

                <div class="review-ajax-container">
                    <div class="review-body">
                        <partial name="~/Views/Shared/Review/_ReviewLimited.cshtml" />
                        @*@await Component.InvokeAsync("UserAvatar", new { userId = @item.User.Id })*@
                    </div>
                </div>
            }
            else
            {
                <h2 class="review-section-heading" id="no-review-yet">
                    No reviews yet!
                </h2>
            }
        </div>
    </div>
</section>
@*End Review section*@