ViewModels/HomePageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MastersOfCinema.ViewModels
{
    public class HomePageViewModel
    {
        public CListsViewModel PopularLists { get; set; }
        //Later check if you really need user!
        public User User { get; set; }

        public List<ReviewViewModel> PopularReviews { get; set; }
        //Highly rated movies - ex. 36 movies
        public List<Movie> HighestRatedMovies { get; set; }
        //user watchlist
        public List<Movie> UserWatchlist { get; set; }
    }
}

Controllers/ListController.cs
using MastersOfCinema.Data;
using MastersOfCinema.Data.Entities;
using MastersOfCinema.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace MastersOfCinema.Controllers
{
    public class ListController : Controller
    {
        private readonly ICinemaRepository _repository;
        private readonly Context _context;
        private readonly ILogger<AccountController> _logger;
        private readonly SignInManager<User> _signInManager;
        private readonly IHttpContextAccessor _userId;

        public ListController(IHttpContextAccessor httpContextAccessor,
            ICinemaRepository repository, Context context, ILogger<AccountController> logger, SignInManager<User> signInManager)
        {
            _repository = repository;
            _context = context;
            _logger = logger;
            _signInManager = signInManager;
            _userId = httpContextAccessor;
        }


        //Displays all of the custom lists of the user!
        public ActionResult Index(int? pageNum)
        {
            CListsViewModel customList = new CListsViewModel();
            if (User.Identity.IsAuthenticated)
            {
                var id = _userId.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                User user = _context.Users.Where(i => i.Id == id).FirstOrDefault();
                //customList.User = user;


                customList = new CListsViewModel()
                {

                    Lists = _repository.GetListsList(),
                    User = user,
                    IsFirstPage = false
                };

            }
            else
            {
                customList = new CListsViewModel()
                {

                    Lists = _repository.GetListsList(),
                    IsFirstPage = false
                };
            }

            int itemsPerPage = 9;
            pageNum = pageNum ?? 0;

            customList.listCount = customList.Lists.Count();

            //first time it's not ajax, next times it is
            bool isAjaxCall = HttpContext.Request.Headers["x-requested-with"] == "XMLHttpRequest";

            if (isAjaxCall)
            {
                var newItems = _repository.GetListsListForAjax(pageNum.Value, itemsPerPage, customList.Lists);
                customList.Lists = newItems;
                return PartialView("Lists/_CListPartial", customList);
            }
            else
            {
                customList.IsFirstPage = true;

                int pageCount = (customList.Lists.ToList().Count() - 1) / itemsPerPage + 1;

                ViewBag.pageCount = pageCount;

                var newItems = _repository.GetListsListForAjax(pageNum.Value, itemsPerPage, customList.Lists);
                customList.Lists = newItems;
                return View(customList);
            }
        }

        //Displays a custom list!
        public ActionResult Details(int? id, int? pageNum)
        {
            if (id == null)
            {
                return NotFound();
            }

            
            var userId = _repository.GetUserCList(id.Value);
            User user = _context.Users.Where(i => i.Id == userId).FirstOrDefault();

            MovieListViewModel customList = new MovieListViewModel()
            {
                Movies = _repository.GetCustomList(id.Value),
                Title = _repository.GetListTitle(id.Value),
                Description = _repository.GetListDescription(id.Value),
                //Directors = _repository.GetAllDirectors(),
                CurrentUser = user,
                IsFirstPage = false
            };

            customList.listCount = customList.Movies.Count();

            int itemsPerPage = 15;
            //page number (starts from 0)
            pageNum = pageNum ?? 0;

            //first time it's not ajax, next times it is
            bool isAjaxCall = HttpContext.Request.Headers["x-requested-with"] == "XMLHttpRequest";

            if (isAjaxCall)
            {
                var newItems = _repository.GetMovieListForAjax(pageNum.Value, itemsPerPage, customList.Movies);
                customList.Movies = newItems;

                return PartialView("Lists/_AjaxMovieListPartial", customList);
            }
            else
            {
                customList.IsFirstPage = true;
                int pageCount = (customList.Movies.ToList().Count() - 1) / itemsPerPage + 1;
                ViewBag.pageCount = pageCount;
                ViewBag.listId = id.ToString();
                var movies = _repository.GetMovieListForAjax(pageNum.Value, itemsPerPage, customList.Movies);
                customList.Movies = movies;
                return View(customList);
            }

        }

        //End Displays a custom list!

        //Begin Create Custom list 
        [HttpGet]
        [Authorize]
        public ActionResult AddList()
        {
            return View();
        }

        //create list
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddList(AddListViewModel newList)
        {

            if (ModelState.IsValid)
            {
                //if user added no movie to the list
                if (newList.MovieId == null)
                {
                    newList.Message = "A list must include at least one film.";
                }
                //if user added one or more movies to the list
                else
                {
                    var UserName = HttpContext.User.Identity.Name;

                    //First we create a record for the list in CList table
                    //Title, Description and user id will be saved there
                    var viewModelObject = new CList
                    {
                        Title = newList.Title,
                        Description = newList.Description,
                        User = _context.Users.FirstOrDefault(u => u.UserName == UserName),
                    };
                    //Insert record
                    _context.Add(viewModelObject);
                    await _context.SaveChangesAsync();

                    //Then we create one record for each movies of the list in ListMovies table
                    //MovieId and List id will be saved there
                    int i = 0;
                    List<ListMovies> viewModelMovie = new List<ListMovies>
                    {

                    };

                    foreach (var item in newList.MovieId)
                    {
                        viewModelMovie.Add(new ListMovies { MovieId = item, CListId = viewModelObject.Id });
                        _context.Add(viewModelMovie[i]);
                        i++;
                    }

                    //Insert record
                    //_context.Add(viewModelMovie);
                    await _context.SaveChangesAsync();

                    return RedirectToAction("Details", new { id = viewModelObject.Id });
                }
            }
            return View(newList);
        }

        //Gets a search term - Display suggestions when user type in input of the live search
        public async Task<IActionResult> Search(string? searchTerm)
        {
            AddListViewModel model = new AddListViewModel()
            {
            };
            model = _repository.GetSuggest(searchTerm);
            return PartialView("Lists/_AjaxAddClistSuggest", model);
        }

        //Add a movie when user clicks on one of the items in the live search suggestions
        public async Task<IActionResult> AddMovieToCList(int? movieIdToAdd)
        {
            AddListViewModel model = new AddListViewModel()
            {
            };
            model.MovieToAdd = _repository.GetMovieById(movieIdToAdd.Value);
            return PartialView("Lists/_AddMoviePartial", model);

        }
        //End custom lists
    }
}

Views/Shared/HomePage/_HighestRatedMovies.cshtml
@model Movie
  
<article class="director-list-item mt-3 mb-2 mt-lg-4 mb-lg-3 col-4 col-md-3 col-lg-2 px-0 px-lg-1">
    <div class="mx-auto">
        @*Movie poster and its tooltip (title (year)) *@
        <div class="movie-poster-wrapper mx-auto">
            <span class="movie-tooltip">@Html.DisplayFor(modelItem => Model.Title) (@Html.DisplayFor(modelItem => Model.Year))</span>
            <a target="_blank" asp-controller="Movie" asp-action="Details" asp-route-id="@Model.Id">
                <img src="@("~/image/"+Model.ImageName)" class="movie-poster" asp-append-version="true" />
            </a>
        </div>
    </div>
</article>

Views/Shared/HomePage/_LikersPopularReview.cshtml
@model ReviewViewModel
@*
    Is created to make the parent view (_Review.cshtml, etx) cleaner
    When rendering the likers of each review, this partial view is being called
*@

@*below each review, there is a section like: x peopla liked this review*@
@if (Model.LikeCount > 0)
{
    <span class="likers-head-wrapper" id="likers-head-wrapper">

        @if (Model.LikeCount == 1 && Model.IsLiked)
        {
            @*The only one who like this review is this user*@
            @*We need to hide the element when user unlikes the review*@
            <span class="review-like-stats" id="like-count" style="display: inline-block;">
                @Model.LikeCount
            </span>
            <span id="review-stats"> likes</span>
        }
        else
        {
            @*Other users liked this review*@
            @*No need to hide/show for this element*@
            <span class="review-like-stats" id="like-count" style="display: inline-block;">
                @Model.LikeCount
            </span>
            <span id="review-stats"> likes</span>
        }
    </span>
}
else
{
    <span class="likers-head-wrapper" id="likers-head-wrapper" style="display: none;">
        @*No one liked this review*@
        @*We need to show the element when user likes the review*@
        <span class="review-like-stats" id="like-count" style="display: inline-block;">
            @Model.LikeCount
        </span>
        <span id="review-stats">
            likes
        </span>
    </span>

}

@*End: x peopla liked this review*@


@*The actual list of likers of a review*@

@*End The actual list of likers of a review*@

Views/Shared/HomePage/_PopularLists.cshtml
@model CList

<article class="director-list-item mt-3 mb-2 mt-lg-4 mb-lg-3 col-12 col-md-6 col-lg-4">
    <div class="mx-auto">
        @*Movie poster and its tooltip (title (year)) *@
        <div class="movie-poster-wrapper list-poster mx-auto">
            <a target="_blank" asp-controller="List" asp-action="Details" asp-route-id="@Model.Id" class="mx-auto">
                <div class="avatars-wrapper">
                    <ul>
                        @foreach (var avatar in Model.Avatars)
                        {
                            if (avatar != "defaultImage")
                            {
                                <li>
                                    <img src="@("~/image/" + avatar)" class="" asp-append-version="true" />
                                </li>
                            }
                            else
                            {
                                <li class="list-avarar-placeholder">
                                </li>
                            }
                        }
                    </ul>
                </div>
            </a>
        </div>

        <a target="_blank" asp-controller="List" asp-action="Details" asp-route-id="@Model.Id" class="clist-title-wrapper">
            <div class="lists-list-title">@Html.DisplayFor(modelItem => Model.Title)</div>
        </a>
        <div class="clist-description">@Html.DisplayFor(modelItem => Model.Description)</div>
        <div class="nav-item ms-md-auto profile-picture-small-wrapper">

                @if (Model.User.ProfilePicture != null)
                {
                    <div class="profile-picture-small">
                        <img class="nav-profile-picture" src="data:image/*;base64,@(Convert.ToBase64String(Model.User.ProfilePicture))">
                        <span class="navbar-user-name">@Model.User.FirstName</span>
                    </div>
                }
                else
                {
                    <div class="profile-picture-small">
                        <i class="fas fa-user-circle me-0 nav-default-profile-picture"></i>
                        <span class="navbar-user-name-default">@Model.User.FirstName</span>
                    </div>
                }

        </div>


    </div>
</article>

Views/Shared/HomePage/_PopularReview.cshtml
@model ReviewViewModel

<div class="box-masonary col-md-6" style="">
    @*<h3 style="background-color: blue">@i2.ToString()</h3>*@
    <div class="a-review">
        @*Movie poster*@
        <div class="popular-review-header container row" style="">
            <div class="reviewed-movie-poster-wrapper ps-0 col-3">
                <div class="movie-poster" style="align-self: flex-start; flex-shrink: 0;">
                    <a target="_blank" asp-controller="Movie" asp-action="Details" asp-route-id="@Model.ReviewdMovie.Id">
                        <img class="img-fluid" src="@("~/image/"+Model.ReviewdMovie.ImageName)" asp-append-version="true" />
                    </a>
                </div>
            </div>
            <div class="header-right-col col-9">
                <div class="reviewer-info">
                    @*Reviewer's avatar is displayed on the left side of each review*@
                    @if (Model.User.ProfilePicture != null)
                    {
                        <div class="profile-picture-small-wrapper">
                            <div class="profile-picture-small">
                                <img class="nav-profile-picture" src="data:image/*;base64,@(Convert.ToBase64String(Model.User.ProfilePicture))">
                                <span class="navbar-user-name">@Model.User.FirstName</span>
                            </div>
                        </div>
                    }
                </div>

                @*Start Movie info*@
                <div class="review-movie-info">
                    <a target="_blank" asp-controller="Movie" asp-action="Details" asp-route-id="@Model.ReviewdMovie.Id">
                        <span class="movie-title fs-3">
                            @Model.ReviewdMovie.Title
                        </span>
                        <span class="movie-year fs-6">
                            @Model.ReviewdMovie.Year
                        </span>
                    </a>
                </div>
                @*End Movie info*@
                @if (@Model.ReviewerRate != null)
                {
                    <div class="reviewer-rate-wrapper d-inline-block">

                        @Model.ReviewerRate
                        @for (var i = 0; i < Model.ReviewerRate; i++)
                        {
                            <span class="starGlowReview" id=""></span>

                        }
                    </div>
                }
            </div>

        </div>



        @*Start Review's right side*@
        <div class="d-inline-block">
            @*Start Review's header*@


            @*Start review text*@
            <div class="review-text-wrapper">
                <div class="review-text">
                    <div class="read-more-object-text" style="white-space: pre-line;">@Model.ReviewText</div>
                </div>
            </div>
            @*End review text*@

            @*Start like section*@
        <div class="review-like-wrapper" style="overflow: hidden;">

            @if (User.Identity.IsAuthenticated)
            {
                @*When clicking on this, review will be liked or unliked*@
                <span class="review-like-button" id="review-like-button">
                    <input type="hidden" value="@Model.Id" class="form-control input-small" id="review-id" />
                    @if (Model.IsLiked)
                    {
                        <span class="review-icon-liked" id="like-icon"></span>
                        <span class="review-liked-text" id="like-caption">Liked</span>
                    }
                    else
                    {
                        <span class="review-icon-like" id="like-icon"></span>
                        <span class="review-like-text" id="like-caption">Like Review</span>
                    }
                </span>
                @*End When clicking on this, review will be liked or unliked*@
            }
            else
            {
                @*if guest user clicked on like, refer him to the login page*@
                <a class="" asp-controller="Account" asp-action="Login" asp-route-returnurl="@Context.Request.Path">
                    <span class="review-like-button" id="">
                        <span class="review-icon-like" id="like-icon"></span>
                        <span class="review-like-text" id="like-caption">Like Review</span>
                    </span>
                </a>
            }

            @*Start Review like stats*@
            <partial name="~/Views/Shared/HomePage/_LikersPopularReview.cshtml" model="Model" />
            @*await Html.PartialAsync("~/Views/Shared/Review/_ReviewLikers.cshtml", item)*@
            @*End Review stats*@

        </div>
            @*End like section*@
        </div>
        @*END Review's right side*@

    </div>
</div>